GET  http://localhost:3000/todos/ HTTP/1.1
Content-Type: application/json

###

GET  http://localhost:3000/todos/get/63bddfa1105f62244dca4af7 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/todos/new HTTP/1.1
Content-Type: application/json

{
    "author": "test",
    "todo": "write a better todo"
}

###

PUT http://localhost:3000/todos/update/63bdddbf105f62244dca4ae9 HTTP/1.1
Content-Type: application/json

{
    "author": "test UPDATE",
    "todo": "Updated to a better todo"
}

###

DELETE http://localhost:3000/todos/delete/63bdddbf105f62244dca4ae9 HTTP/1.1
Content-Type: application/json

###